### ISSUE TITLE
no token send error

### ISSUE THREAD

**Issue by weput** [flaviocopes/grav-plugin-shoppingcart-paypal#6] opened 2017-04-06 13:52 UTC
Hello

I'm facing this no token issue... and honestly have no idea what to look for in order to fix it.

**Comment by flaviocopes** [comment] 2017-04-07 17:48
Closing as duplicate of https://github.com/flaviocopes/grav-plugin-shoppingcart/issues/59

**Closed by flaviocopes** 2017-04-07 17:48 UTC
